In [7]:
import pandas as pd

In [1]:
import requests

cookies = {
    'TMSESSID': 'ce7c7c5cf279babea3abb26b54ac9ae1',
    '_sp_v1_ss': '1:H4sIAAAAAAAAAItWqo5RKimOUbKKxs_IAzEMamN1YpRSQcy80pwcILsErKC6lpoSSrEA-EAOLpYAAAA%3D',
    '_sp_v1_p': '706',
    '_sp_v1_data': '746536',
    'euconsent-v2': 'CP6RzMAP6RzMAAGABCENAmEsAP_gAEPAACawJDgBdDJECCFAIXBSAOsQKIEVUVABAEAAAAABACABQAAAIAQCkAAAAACAAiAAARAAIEQAAAAAAAAABAAAAIAAIAAEAAAQgAAIIAAAAAAAAABAAAAIAAAAQAAAgAABAAQAkACIAAIAUEAAAAACAAAQAIAAAIAAAgAAAAAAAAAAAAIIICgAAAAAAAAAAAACABAAAAAIH7wEQAFAAOAEUAI4AcgBCACIgE7ALEAXUA14B2wF0AMEAZCAyYB-4BgSAmABUADgAIIAZABoAEQAJgAZgA3gB6AD8AIQAQwAmgBlAD9AUeAvMBkgDcwoAIARQC6B0BkACoAHAAQQAyADQAIgATIAuAC6AGIAMwAbwA9AB-AEMAJoAZQA_QCLAFiAReAo8BVgC8wGSAMsAcWPAAgCKHAAQG5kIA4ATAAuABiADeAHoARwCrCAAEAchKAUABwAIgATAAuABiAEMAi8BR4C8wGSEgAIDLC0AIARwCrCkBMACoAHAAQAA0ACIAEwAMQAZgA_ACGAGUAP0AiwB7QEXgKsAXmAyQBlhQAIADIALYA5AG5g.YAAAAAAAAAAA',
    'consentUUID': '0934e3a3-90d0-4e44-8622-aca283b4042b_29',
    'kndctr_B21B678254F601E20A4C98A5_AdobeOrg_identity': 'CiY4ODMxNzkxNDE4NzUzMjI4NzY0MjYwODgyOTU3NjE5ODY1MDM5OFIRCPDT1qbcMRgBKgRTR1AzMAHwAfDT1qbcMQ==',
    'kndctr_B21B678254F601E20A4C98A5_AdobeOrg_cluster': 'sgp3',
    'AMCV_B21B678254F601E20A4C98A5%40AdobeOrg': 'MCMID|88317914187532287642608829576198650398',
    '_ga': 'GA1.2.104989476.1708404356',
    '_gid': 'GA1.2.195225017.1708404356',
}

headers = {
    'authority': 'www.transfermarkt.us',
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'accept-language': 'en,zh-CN;q=0.9,zh;q=0.8,en-GB;q=0.7,en-US;q=0.6',
    'cache-control': 'max-age=0',
    # 'cookie': 'TMSESSID=ce7c7c5cf279babea3abb26b54ac9ae1; _sp_v1_ss=1:H4sIAAAAAAAAAItWqo5RKimOUbKKxs_IAzEMamN1YpRSQcy80pwcILsErKC6lpoSSrEA-EAOLpYAAAA%3D; _sp_v1_p=706; _sp_v1_data=746536; euconsent-v2=CP6RzMAP6RzMAAGABCENAmEsAP_gAEPAACawJDgBdDJECCFAIXBSAOsQKIEVUVABAEAAAAABACABQAAAIAQCkAAAAACAAiAAARAAIEQAAAAAAAAABAAAAIAAIAAEAAAQgAAIIAAAAAAAAABAAAAIAAAAQAAAgAABAAQAkACIAAIAUEAAAAACAAAQAIAAAIAAAgAAAAAAAAAAAAIIICgAAAAAAAAAAAACABAAAAAIH7wEQAFAAOAEUAI4AcgBCACIgE7ALEAXUA14B2wF0AMEAZCAyYB-4BgSAmABUADgAIIAZABoAEQAJgAZgA3gB6AD8AIQAQwAmgBlAD9AUeAvMBkgDcwoAIARQC6B0BkACoAHAAQQAyADQAIgATIAuAC6AGIAMwAbwA9AB-AEMAJoAZQA_QCLAFiAReAo8BVgC8wGSAMsAcWPAAgCKHAAQG5kIA4ATAAuABiADeAHoARwCrCAAEAchKAUABwAIgATAAuABiAEMAi8BR4C8wGSEgAIDLC0AIARwCrCkBMACoAHAAQAA0ACIAEwAMQAZgA_ACGAGUAP0AiwB7QEXgKsAXmAyQBlhQAIADIALYA5AG5g.YAAAAAAAAAAA; consentUUID=0934e3a3-90d0-4e44-8622-aca283b4042b_29; kndctr_B21B678254F601E20A4C98A5_AdobeOrg_identity=CiY4ODMxNzkxNDE4NzUzMjI4NzY0MjYwODgyOTU3NjE5ODY1MDM5OFIRCPDT1qbcMRgBKgRTR1AzMAHwAfDT1qbcMQ==; kndctr_B21B678254F601E20A4C98A5_AdobeOrg_cluster=sgp3; AMCV_B21B678254F601E20A4C98A5%40AdobeOrg=MCMID|88317914187532287642608829576198650398; _ga=GA1.2.104989476.1708404356; _gid=GA1.2.195225017.1708404356',
    'dnt': '1',
    'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'none',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0',
}

In [2]:
from bs4 import BeautifulSoup

In [4]:
soup = BeautifulSoup(html_string, 'html.parser')
tables = soup.find_all('table', {'class': "auflistung"})
print(tables)

NameError: name 'html_string' is not defined

In [5]:
data=[]
import time
for i in range(1992,2023):
    year=str(i)
    print(year,"start")

    params = {
        'saison_id': year,
    }



    response = requests.get(
        'https://www.transfermarkt.us/premier-league/trainerwechsel/wettbewerb/GB1/plus/1',
        params=params,
        cookies=cookies,
        headers=headers,
    )

    html_string=response.text


    soup = BeautifulSoup(html_string, 'html.parser')
    tables = soup.find_all('table', {'class': "items"})[0]
    
    tbody = tables.find_all('tbody')[0]
    tr=tbody.find_all('tr',recursive=False)[1:]
    for t in tr:
        init={}
        td=t.find_all('td',recursive=False)
        if len(td)!=12:
            continue
            
        club = td[0].find_all('img')[0].get('alt', '')
        init["club"]=club
        
        Coach = td[1].find_all('img')[0].get('alt', '')
        init["Coach"]=Coach
    
        init["Matchday"]=td[2].get_text(strip=True)
    
        init["Rank"]=td[3].get_text(strip=True)
    
        init["PPG"]=td[4].get_text(strip=True)
    
        try:
            last_match_teams_rank=td[5].find_all('span',recursive=False)[0].get_text(strip=True)
        except:
            last_match_teams_rank=""
            
        last_match_teams=f" {last_match_teams_rank} ".join([x.get('title', '') for x in td[5].find_all('a',recursive=False)])
        init["last_match"]=last_match_teams
            
        init["last_match_teams_rank"]=last_match_teams_rank
        
        init["Leaving date"]=td[6].get_text(strip=True)
    
        init["Days in charge"]=td[7].get_text(strip=True)
    
        init["Successor"] = td[8].find_all('img')[0].get('alt', '')
    
        init["Rank1"] = td[9].get_text(strip=True)
        init["PPG1"]=td[10].get_text(strip=True)
        
        try:
            first_match_teams_rank=td[11].find_all('span',recursive=False)[0].get_text(strip=True)
        except:
            first_match_teams_rank=""
            
        first_match_teams=f" {first_match_teams_rank} ".join([x.get('title', '') for x in td[5].find_all('a',recursive=False)])
        init["first_match"]=first_match_teams

        init["year"]=year
        
        data.append(init)
    print(year,"end")

1992 start
1992 end
1993 start
1993 end
1994 start
1994 end
1995 start
1995 end
1996 start
1996 end
1997 start
1997 end
1998 start
1998 end
1999 start
1999 end
2000 start
2000 end
2001 start
2001 end
2002 start
2002 end
2003 start
2003 end
2004 start
2004 end
2005 start
2005 end
2006 start
2006 end
2007 start
2007 end
2008 start
2008 end
2009 start
2009 end
2010 start
2010 end
2011 start
2011 end
2012 start
2012 end
2013 start
2013 end
2014 start
2014 end
2015 start
2015 end
2016 start
2016 end
2017 start
2017 end
2018 start
2018 end
2019 start
2019 end
2020 start
2020 end
2021 start
2021 end
2022 start
2022 end

In [8]:
df = pd.DataFrame(data)
df.to_csv('output.csv', index=False)

In [9]:
df

,club,Coach,Matchday,Rank,PPG,last_match,last_match_teams_rank,Leaving date,Days in charge,Successor,Rank1,PPG1,first_match,year
0,Chelsea FC,David Webb,42,11,1.46,Sheffield United 4:2 Chelsea FC,4:2,"Jun 30, 1993",134,Glenn Hoddle,-,-,Sheffield United Chelsea FC,1992
1,Tottenham Hotspur,Doug Livermore,37,7,1.40,Arsenal FC 1:3 Tottenham Hotspur,1:3,"Jun 19, 1993",388,Osvaldo Ardiles,-,-,Arsenal FC Tottenham Hotspur,1992
2,Tottenham Hotspur,Ray Clemence,-,-,-,,,"Jun 19, 1993",388,Osvaldo Ardiles,-,-,,1992
3,Crystal Palace,Steve Coppell,42,20,1.17,Arsenal FC 3:0 Crystal Palace,3:0,"May 17, 1993",3209,Alan Smith,-,-,Arsenal FC Crystal Palace,1992
4,Nottingham Forest,Brian Clough,42,22,0.95,Ipswich Town 2:1 Nottingham Forest,2:1,"May 8, 1993",6700,Frank Clark,-,-,Ipswich Town Nottingham Forest,1992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,Wolverhampton Wanderers,Bruno Lage,9,18,0.75,West Ham United 2:0 Wolverhampton Wanderers,2:0,"Oct 2, 2022",458,Steve Davis,20,0.57,West Ham United 3:0 Wolverhampton Wanderers,2022
406,Brighton & Hove Albion,Andrew Crofts,-,-,-,,,"Sep 17, 2022",9,Roberto De Zerbi,6,1.53,,2022
407,Chelsea FC,Thomas Tuchel,6,6,1.67,GNK Dinamo Zagreb 1:0 Chelsea FC,1:0,"Sep 7, 2022",589,Graham Potter,11,1.27,GNK Dinamo Zagreb 1:1 Chelsea FC,2022
408,Brighton & Hove Albion,Graham Potter,6,4,2.17,Brighton & Hove Albion 5:2 Leicester City,5:2,"Sep 7, 2022",1206,Andrew Crofts,-,-,Brighton & Hove Albion Leicester City,2022
409,AFC Bournemouth,Scott Parker,4,17,0.75,Liverpool FC 9:0 AFC Bournemouth,9:0,"Aug 30, 2022",425,Gary O'Neil,15,1.18,Liverpool FC 0:0 AFC Bournemouth,2022